---
title: "scraping_1"
---

```{r, message = FALSE}
#loading libraries
library(rvest)
library(data.table)
library(dplyr)
library(readr)
library(ggplot2)
library(scales)
library(gridExtra)
library(tidyr)
```

```{r}
##Specifying the url for desired website to be scraped
t <-  read_html("https://hoopshype.com/salaries/players/")
write_html(t, "t.html")
```

```{r}
(my_list <-  
  t %>% 
  html_table())
```


```{r}
class(my_list)
```

```{r}
#converting to df
df <- my_list[[1]]
df
```

```{r}
#check
class(df)
```


```{r}
#rename first column
df[1,1] <- 'Index'
df
```

```{r}
#renaming column names
names(df) <- as.character(df[1,])
```


```{r}
#delete obsolete row 
(df <- df[-1,])
df <- df %>% 
  rename(
    fy_2019_20 = `2019/20`,
    fy_2020_21 = `2020/21`,
    fy_2021_22 = `2021/22`,
    fy_2022_23 = `2022/23`,
    fy_2023_24 = `2023/24`,
    fy_2024_25 = `2024/25`,
    )
df
```


```{r}
#convertin chr to dbl
df[,-2] <- sapply(df[,-2], parse_number)
df
```


```{r}
#2019/2020
(f1 <- df[1:10,] %>% ggplot( aes(x=reorder(Player, fy_2019_20), y=fy_2019_20)) +
  geom_bar(stat="identity", aes(fill= -fy_2019_20))+
  coord_flip(ylim=c(25000000,45000000))+
  labs(title = "Figure 1. Top 10 NBA Salaries in 2019/2020", x = "Salary in USD", y = "Player Name")+
  scale_y_continuous( breaks= c(seq(25000000,45000000, by = 5000000)),labels = comma)+
  theme(legend.position="none") +
  geom_text(aes(label = scales::dollar(fy_2019_20)), vjust=0.4, hjust=1.3, color="white",
            position = position_dodge(0.9), size=3.5))
  
```



```{r}
#2019/2020
(f2 <- df[1:10,] %>% ggplot( aes(x=reorder(Player, fy_2020_21), y=fy_2020_21)) +
  geom_bar(stat="identity", aes(fill= -fy_2020_21))+
  coord_flip(ylim=c(25000000,45000000))+
  labs(title = "Figure 2. Top 10 NBA Salaries in 2020/2021", x = "Salary in USD", y = "Player Name")+
  scale_y_continuous( breaks= c(seq(25000000,45000000, by = 5000000)),labels = comma)+
  theme(legend.position="none") +
  geom_text(aes(label = scales::dollar(fy_2020_21)), vjust=0.4, hjust=1.3, color="white",
            position = position_dodge(0.9), size=3.5))
```


```{r}
#converting to tidy format
df_tidy <- df %>% 
  gather (fy, salary,fy_2019_20:fy_2024_25) %>% 
  arrange(fy)
df_tidy
```


```{r}
(f3 <- df_tidy %>% filter(Player == "Stephen Curry", salary >0) %>% 
  ggplot( aes(x=fy, y=salary)) +
  geom_bar(stat="identity", aes(fill= -salary))+
  labs(title = "Figure 3. Stephen Curry Salary in Seasons 2019 - 2022", y = "Season", y = "Salary, in USD")+
  scale_y_continuous( breaks= c(seq(35000000,50000000, by = 5000000)),labels = comma)+
  coord_cartesian(ylim=c(35000000,46000000))+
  theme(legend.position="none", axis.text.y = element_text(size = 10, angle = 45)) +
  geom_text(aes(label = scales::dollar(salary)), vjust=2.9, hjust=0.5, color="white",
            position = position_dodge(0.9), size=3.5))
```

```{r}
ggsave("Top 10 NBA Salaries 2019-2020.png", plot = f1)
ggsave("Top 10 NBA Salaries 2020-2021.png", plot = f2)
ggsave("Stephen Curry Salary for 3 seasons.png", plot = f3)
```


```{r}
saveRDS(df, file="NBA_salaries.Rda")
saveRDS(df, file="NBA_salaries_tidy.Rda")
```

